apiVersion: v1
data:
  piped-config.yaml: |-
    apiVersion: pipecd.dev/v1beta1
    kind: Piped
    spec:
      projectID: quickstart
      pipedID: 322c9b6e-5778-4cd7-a272-ef696487de9d
      pipedKeyData: cnNzbHR3bW5mcDE0cGVkbXd1MTRqY3R4cGdobnhjcmgzYnJ5eDRrcWQzYmptdGN6czI=
      apiAddress: pipecd:8080
      syncInterval: 1m
      repositories:
        - repoId: examples
          remote: https://github.com/pipe-cd/examples.git
          branch: master
        - repoId: my-repo
          remote: https://github.com/Ayushmore1214/pipecd-hello-app.git
          branch: main
      plugins:
        - name: kubernetes # kubernetes plugin version: v0.3.0
          port: 7001
          url: https://github.com/pipe-cd/pipecd/releases/download/pkg%2Fapp%2Fpipedv1%2Fplugin%2Fkubernetes%2Fv0.3.0/kubernetes_v0.3.0_linux_amd64
          deployTargets:
            - name: kubernetes-local
              config:
                kubectlVersion: 1.33.0
        - name: wait # wait plugin version: v0.1.1
          port: 7002
          url: https://github.com/pipe-cd/pipecd/releases/download/pkg%2Fapp%2Fpipedv1%2Fplugin%2Fwait%2Fv0.1.1/wait_v0.1.1_linux_amd64
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"piped-config.yaml":"apiVersion: pipecd.dev/v1beta1\nkind: Piped\nspec:\n  projectID: quickstart\n  pipedID: 322c9b6e-5778-4cd7-a272-ef696487de9d\n  pipedKeyData: cnNzbHR3bW5mcDE0cGVkbXd1MTRqY3R4cGdobnhjcmgzYnJ5eDRrcWQzYmptdGN6czI=\n  apiAddress: pipecd:8080\n  syncInterval: 1m\n  repositories:\n    - repoId: examples\n      remote: https://github.com/pipe-cd/examples.git\n      branch: master\n  plugins:\n    - name: kubernetes # kubernetes plugin version: v0.3.0\n      port: 7001\n      url: https://github.com/pipe-cd/pipecd/releases/download/pkg%2Fapp%2Fpipedv1%2Fplugin%2Fkubernetes%2Fv0.3.0/kubernetes_v0.3.0_linux_amd64\n      deployTargets:\n        - name: kubernetes-local\n          config:\n            kubectlVersion: 1.33.0\n    - name: wait # wait plugin version: v0.1.1\n      port: 7002\n      url: https://github.com/pipe-cd/pipecd/releases/download/pkg%2Fapp%2Fpipedv1%2Fplugin%2Fwait%2Fv0.1.1/wait_v0.1.1_linux_amd64"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"pipedv1-exp","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"pipedv1-exp","app.kubernetes.io/version":"v1.0.0-alpha1","helm.sh/chart":"pipedv1-exp-v1.0.0-alpha1"},"name":"pipedv1-exp","namespace":"pipecd"}}
  creationTimestamp: "2026-03-23T02:57:35Z"
  labels:
    app.kubernetes.io/instance: pipedv1-exp
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: pipedv1-exp
    app.kubernetes.io/version: v1.0.0-alpha1
    helm.sh/chart: pipedv1-exp-v1.0.0-alpha1
  name: pipedv1-exp
  namespace: pipecd
  resourceVersion: "1122"
  uid: ca003745-dfc4-4729-bfaf-7dcf2d0f42a5
