apiVersion: pipecd.dev/v1beta1
kind: Application
spec:
  name: pipecd-app

  platformProvider: kubernetes

  pipeline:
    stages:
      - name: K8S_SYNC

  source:
    repoURL: https://github.com/Ayushmore1214/pipecd-hello-app
    repoId: my-repo
    path: k8s
    targetRevision: main

  destination:
    cluster: kubernetes-local
    namespace: default